//reads all the users(request to protucted rought)
GET http://localhost:4000/user-api/users

###
GET http://localhost:4000/user-api/user

###
//create new user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username":"nishika",
    "password":"omgggg",
    "email":"nishika0205@gmail.com",
    "age":20
}

###
//updates rhe user
# PUT http://localhost:4000/user-api/users/69aa8da20e12fe8c54671fe9
# Content-Type: application/json

# {
#         "username":"bhamummm",
#     "password":"omgm",
#     "email":"nishika000205@gmail.com",
#     "age":20
# }

###
DELETE http://localhost:4000/user-api/users/69aa8da20e12fe8c54671fe9
###
//adding to the cart 

###
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "email":"nishika0205@gmail.com",
    "password":"omgggg"
}
###
PUT http://localhost:4000/user-api/cart/product-id/69b23c456da9a2e83a0af57d
###
//
//read all products 
GET http://localhost:4000/product-api/products

###
// read product by id
GET http://localhost:4000/product-api/products/69aaf500250a57980a195daf

###
// create new product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
	"productId":"P1023",
	"productName":"laptop",
	"brand":"victus",
	"price":20000
}

###
// update a product
PUT http://localhost:4000/product-api/products/69b23c456da9a2e83a0af57d
Content-Type: application/json

{
	"productId":"P101",
	"productName":"laptop",
	"brand":"hp",
	"price":40000
}

###
### delete a product by id
DELETE http://localhost:4000/product-api/products/69aaf500250a57980a195daf
